version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: testdb
            POSTGRES_PASSWORD: password
        volumes:
            - ./local-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 3s
            timeout: 5s
            retries: 5
